### ISSUE TITLE
Start using issues and GitHub automated project boards! 🔥

### ISSUE THREAD

**Issue by OliverBrotchie** [hw-cs-reps/portal#2]
Its great for your GitHub history, its great for tracking progress, it lets people know what needs done and what stage the project is at.

**Comment by humaidq** [comment]
Hey! We are using a `TODO.md` file in the [platform](https://github.com/hw-cs-reps/platform/blob/master/TODO.md) project, which is a vertical kanban board. Since this is a small project, it seems to be an adequate to use that.

And personally I find it to be more efficient, as I don't have to go to the GitHub to tick off a task. I'll probably add a `TODO.md` to this repository sometime soon.

**Comment by OliverBrotchie** [comment]
Okay great! It was just a suggestion so that people looking at the repo can help out easier.

**Comment by humaidq** [comment]
> Okay great! It was just a suggestion so that people looking at the repo can help out easier.

Yes, we like to be as welcoming to contributors. Thank you for pointing it out. I'll keep it opened until we add a `TODO.md` file.
